version: "3.8"

services:
  redis_cache:
    image: redis:7-alpine
    container_name: quant_redis
    ports:
      - "6379:6379"

  quant_engine:
    build: .
    container_name: quant_engine
    ports:
      - "3000:3000" # Exposes the Fastify Auth server to your local browser
    volumes:
      - ./:/app # Syncs your VS Code files live into the container
      - /app/node_modules # Prevents local Windows/Mac node_modules from crashing Linux
    env_file:
      - .env
    depends_on:
      - redis_cache
